// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstate.Infrastructure.Persistence;

#nullable disable

namespace RealEstate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260904023937_AddCommercialAndLandPropertyTaxonomy")]
    partial class AddCommercialAndLandPropertyTaxonomy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealEstate.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("LogoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LogoStoredFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Agencies", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.AgencyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AgencyId", "NormalizedEmail")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("AgencyInvitations", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.AgencyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserId");

                    b.HasIndex("AgencyId", "UserId")
                        .IsUnique();

                    b.ToTable("AgencyMembers", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSquareMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("BalconyCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Bathrooms")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FurnishingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("GeocodedDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GeocodingProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GeocodingResultReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool?>("HasBasement")
                        .HasColumnType("boolean");

                    b.Property<string>("HeatingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<bool?>("IsExchangePossible")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LocationConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationPrecision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Rooms")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.Property<int?>("YearRenovated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Listings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Listings_Location_CoordinatePair", "(\r\n    \"Latitude\" IS NULL\r\n    AND \"Longitude\" IS NULL\r\n)\r\nOR (\r\n    \"Latitude\" IS NOT NULL\r\n    AND \"Longitude\" IS NOT NULL\r\n)");

                            t.HasCheckConstraint("CK_Listings_Location_DisplayNameTrimmedNonBlank", "\"GeocodedDisplayName\" IS NULL\r\nOR (\r\n    \"GeocodedDisplayName\" <> ''\r\n    AND \"GeocodedDisplayName\" = btrim(\"GeocodedDisplayName\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_Listings_Location_LatitudeRange", "\"Latitude\" IS NULL OR \"Latitude\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Listings_Location_LongitudeRange", "\"Longitude\" IS NULL OR \"Longitude\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_Listings_Location_PrecisionDefined", "\"LocationPrecision\" IS NULL\r\nOR \"LocationPrecision\" IN (\r\n    'ExactAddress',\r\n    'Street',\r\n    'Neighborhood',\r\n    'Municipality',\r\n    'City',\r\n    'Approximate')");

                            t.HasCheckConstraint("CK_Listings_Location_ProviderKeyTrimmedNonBlank", "\"GeocodingProviderKey\" IS NULL\r\nOR (\r\n    \"GeocodingProviderKey\" <> ''\r\n    AND \"GeocodingProviderKey\" = btrim(\"GeocodingProviderKey\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_Listings_Location_ResultReferenceTrimmedNonBlank", "\"GeocodingResultReference\" IS NULL\r\nOR (\r\n    \"GeocodingResultReference\" <> ''\r\n    AND \"GeocodingResultReference\" = btrim(\"GeocodingResultReference\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_Listings_Location_SnapshotState", "(\r\n    \"Latitude\" IS NULL\r\n    AND \"Longitude\" IS NULL\r\n    AND \"LocationPrecision\" IS NULL\r\n    AND \"GeocodingProviderKey\" IS NULL\r\n    AND \"GeocodingResultReference\" IS NULL\r\n    AND \"GeocodedDisplayName\" IS NULL\r\n    AND \"LocationConfirmedAtUtc\" IS NULL\r\n)\r\nOR (\r\n    \"Latitude\" IS NOT NULL\r\n    AND \"Longitude\" IS NOT NULL\r\n    AND (\r\n        (\r\n            \"LocationPrecision\" IS NULL\r\n            AND \"GeocodingProviderKey\" IS NULL\r\n            AND \"GeocodingResultReference\" IS NULL\r\n            AND \"GeocodedDisplayName\" IS NULL\r\n            AND \"LocationConfirmedAtUtc\" IS NULL\r\n        )\r\n        OR (\r\n            \"LocationPrecision\" IS NOT NULL\r\n            AND \"GeocodingProviderKey\" IS NOT NULL\r\n            AND \"GeocodingResultReference\" IS NOT NULL\r\n            AND \"LocationConfirmedAtUtc\" IS NOT NULL\r\n        )\r\n    )\r\n)");
                        });
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingApartmentDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.ToTable("ListingApartmentDetails", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingCommercialDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommercialType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.HasKey("ListingId");

                    b.ToTable("ListingCommercialDetails", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingHouseDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<decimal?>("YardAreaSquareMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("ListingId");

                    b.ToTable("ListingHouseDetails", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true");

                    b.HasIndex("ListingId", "SortOrder");

                    b.ToTable("ListingImages", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingLandDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("LandType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.HasKey("ListingId");

                    b.ToTable("ListingLandDetails", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "LanguageCode")
                        .IsUnique();

                    b.HasIndex("Title", "City", "Municipality", "Neighborhood")
                        .HasDatabaseName("IX_ListingTranslations_Q_Trigram");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "City", "Municipality", "Neighborhood"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title", "City", "Municipality", "Neighborhood"), new[] { "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops" });

                    b.ToTable("ListingTranslations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ListingTranslations_AddressLine_TrimmedNonBlank", "\"AddressLine\" IS NULL\r\nOR (\r\n    \"AddressLine\" <> ''\r\n    AND \"AddressLine\" = btrim(\"AddressLine\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_ListingTranslations_City_TrimmedNonBlank", "\"City\" IS NULL\r\nOR (\r\n    \"City\" <> ''\r\n    AND \"City\" = btrim(\"City\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_ListingTranslations_Description_TrimmedNonBlank", "\"Description\" IS NULL\r\nOR (\r\n    \"Description\" <> ''\r\n    AND \"Description\" = btrim(\"Description\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_ListingTranslations_LanguageCode_Canonical", "\"LanguageCode\" <> ''\r\nAND \"LanguageCode\" = btrim(\"LanguageCode\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\nAND \"LanguageCode\" = lower(\"LanguageCode\")\r\nAND \"LanguageCode\" ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})*$'");

                            t.HasCheckConstraint("CK_ListingTranslations_Municipality_TrimmedNonBlank", "\"Municipality\" IS NULL\r\nOR (\r\n    \"Municipality\" <> ''\r\n    AND \"Municipality\" = btrim(\"Municipality\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_ListingTranslations_Neighborhood_TrimmedNonBlank", "\"Neighborhood\" IS NULL\r\nOR (\r\n    \"Neighborhood\" <> ''\r\n    AND \"Neighborhood\" = btrim(\"Neighborhood\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))\r\n)");

                            t.HasCheckConstraint("CK_ListingTranslations_Title_TrimmedNonBlank", "\"Title\" <> ''\r\nAND \"Title\" = btrim(\"Title\", chr(9) || chr(10) || chr(11) || chr(12) || chr(13) || chr(32) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288))");
                        });
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("AvatarSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarStoredFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.AgencyInvitation", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RealEstate.Domain.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstate.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Agency");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.AgencyMember", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Agency", "Agency")
                        .WithMany("Members")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstate.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Listing", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealEstate.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingApartmentDetails", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithOne("ApartmentDetails")
                        .HasForeignKey("RealEstate.Domain.Entities.ListingApartmentDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingCommercialDetails", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithOne("CommercialDetails")
                        .HasForeignKey("RealEstate.Domain.Entities.ListingCommercialDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingHouseDetails", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithOne("HouseDetails")
                        .HasForeignKey("RealEstate.Domain.Entities.ListingHouseDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingImage", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingLandDetails", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithOne("LandDetails")
                        .HasForeignKey("RealEstate.Domain.Entities.ListingLandDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.ListingTranslation", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Listing", "Listing")
                        .WithMany("Translations")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Listing", b =>
                {
                    b.Navigation("ApartmentDetails");

                    b.Navigation("CommercialDetails");

                    b.Navigation("HouseDetails");

                    b.Navigation("Images");

                    b.Navigation("LandDetails");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
